# Generated by Django 5.1.7 on 2026-06-09 23:23

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ascensor', 'Ascensores'), ('aire_acondicionado', 'Aire acondicionado'), ('seguridad', 'Sistemas de seguridad y control'), ('incendios', 'Sistema contra incendios'), ('electrico', 'Instalaciones eléctricas'), ('plomeria', 'Plomería y sanitarios'), ('generadores', 'Generadores y respaldo eléctrico'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('frecuencia_preventiva', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('fecha_base_programacion', models.DateField(help_text='Fecha de referencia para el cronograma anual')),
                ('proveedor_servicio', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, help_text='Área destino si no hay equipo asociado', max_length=200)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
                ('proveedor', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='unidad', max_length=50)),
                ('ubicacion_instalacion', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.equipo')),
            ],
            options={
                'verbose_name': 'Compra / Insumo',
                'verbose_name_plural': 'Compras e insumos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoCorrectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='Área o zona del edificio', max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='reportado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_correctivos', to='core.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento correctivo',
                'verbose_name_plural': 'Mantenimientos correctivos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del trabajo')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_preventivos', to='core.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento preventivo',
                'verbose_name_plural': 'Mantenimientos preventivos',
                'ordering': ['fecha_programada'],
                'unique_together': {('equipo', 'fecha_programada')},
            },
        ),
    ]
