# Generated by Django 5.1.7 on 2026-06-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprainsumo',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('galon', 'Galón'), ('litro', 'Litro'), ('metro', 'Metro'), ('kilogramo', 'Kilogramo'), ('caja', 'Caja'), ('rollo', 'Rollo'), ('bolsa', 'Bolsa'), ('saco', 'Saco'), ('kit', 'Kit'), ('par', 'Par')], default='unidad', max_length=50),
        ),
    ]
