# Generated by Django 5.1.7 on 2026-06-21 15:49

from django.db import migrations, models


LEGACY_CATEGORIA_MAP = {
    'ascensor': 'ascensores',
    'aire_acondicionado': 'aire_acondicionado_termosistemas',
    'seguridad': 'sistemas_seguridad_control',
    'incendios': 'sistemas_contra_incendio',
    'electrico': 'instalaciones_electricas',
    'plomeria': 'instalaciones_sanitarias',
    'generadores': 'grupos_electrogenos',
    'otros': 'varios',
}


def migrar_categorias_equipo(apps, schema_editor):
    Equipo = apps.get_model('core', 'Equipo')
    for equipo in Equipo.objects.all():
        nueva = LEGACY_CATEGORIA_MAP.get(equipo.categoria)
        if nueva and nueva != equipo.categoria:
            equipo.categoria = nueva
            equipo.save(update_fields=['categoria'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_correctivo_prioridad_default'),
    ]

    operations = [
        migrations.RunPython(migrar_categorias_equipo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('acelerografo', 'Acelerógrafo'), ('ascensores', 'Ascensores'), ('barreras_peatonales', 'Barreras peatonales'), ('barreras_vehiculares', 'Barreras vehiculares'), ('bombas_agua_desague', 'Bombas de agua y desagüe'), ('charlas_simulacros', 'Charlas y simulacros'), ('desinfeccion', 'Desinfección'), ('desratizacion', 'Desratización'), ('equipos_extraccion_monoxido', 'Equipos de extracción de monóxido'), ('equipos_inyeccion_aire', 'Equipos de inyección de aire'), ('equipos_presurizacion_escaleras', 'Equipos de presurización de escaleras'), ('equipos_ventilacion_mecanica', 'Equipos de ventilación mecánica'), ('escaleras_electricas', 'Escaleras eléctricas'), ('estructuras_metalicas', 'Estructuras metálicas'), ('extintores', 'Extintores'), ('fumigacion', 'Fumigación'), ('grupos_electrogenos', 'Grupos electrógenos'), ('iluminacion_externa_fachada', 'Iluminación externa de fachada'), ('impermeabilizacion_manto_asfaltico', 'Impermeabilización | Manto asfáltico'), ('inspeccion_muro_cortina', 'Inspección de muro cortina'), ('limpieza_cisternas', 'Limpieza de cisternas'), ('limpieza_fachadas', 'Limpieza de fachadas'), ('luces_emergencia', 'Luces de emergencia'), ('mamparas', 'Mamparas'), ('plataforma_discapacidad', 'Plataforma para personas con discapacidad'), ('pozos_tierra', 'Pozos a tierra'), ('pozos_sumideros', 'Pozos sumideros'), ('puertas_corta_fuego', 'Puertas corta fuego'), ('puertas_vehiculares', 'Puertas vehiculares'), ('aire_acondicionado_termosistemas', 'Sistema de aire acondicionado (Termosistemas)'), ('aire_acondicionado_johnson', 'Sistema de aire acondicionado (Johnson Controls)'), ('ablandador_agua', 'Ablandador de agua'), ('sistemas_contra_incendio', 'Sistemas contra incendio'), ('sistemas_seguridad_control', 'Sistemas de seguridad y control'), ('sub_estacion_electrica', 'Sub estación eléctrica'), ('tableros_transferencia_distribucion', 'Tableros de transferencia | Distribución | Otros relacionados'), ('tableros_electricos', 'Tableros eléctricos'), ('ups', 'UPS'), ('alfombras_cortinas_otros', 'Alfombras, cortinas y otros'), ('anclajes_davits_soportes', 'Anclajes | Davits | Soportes *'), ('baldosas_cielo_raso', 'Baldosas y cielo raso'), ('carpinteria', 'Carpintería'), ('cerrajeria', 'Cerrajería'), ('equipos_computo', 'Equipos de cómputo *'), ('equipos_multimedia', 'Equipos y sistemas multimedia*'), ('fachadas', 'Fachadas'), ('ferreteria_herramientas', 'Ferretería y herramientas'), ('gestion_residuos', 'Gestión de residuos'), ('granito', 'Granito'), ('instalaciones_electricas', 'Instalaciones eléctricas'), ('instalaciones_sanitarias', 'Instalaciones sanitarias'), ('jardineria', 'Jardinería'), ('limpieza_estacionamientos', 'Limpieza de estacionamientos'), ('materiales_sshh_ambientadores', 'Materiales de SSHH y ambientadores'), ('paredes_techos_pisos_enchapes', 'Paredes | Techos | Pisos | Enchapes'), ('pintura', 'Pintura'), ('recarga_combustible', 'Recarga de combustible'), ('sala_usos_multiples', 'Sala de usos múltiples (SUM)'), ('suministro_sal', 'Suministro de sal'), ('suministro_productos_quimicos', 'Suministro y servicio de productos químicos'), ('suministros_seguridad', 'Suministros de seguridad'), ('comunicaciones', 'Comunicaciones'), ('varios', 'Varios')], default='varios', max_length=80),
        ),
    ]
